# Generated by ariadne-codegen
# Source: schema.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    ActorType,
    AuditLogOrderField,
    CheckAnnotationLevel,
    CheckConclusionState,
    CheckRunType,
    CheckStatusState,
    CommitContributionOrderField,
    DeploymentOrderField,
    DeploymentStatusState,
    DiffSide,
    DiscussionCloseReason,
    DiscussionOrderField,
    DiscussionPollOptionOrderField,
    DismissReason,
    EnterpriseAdministratorInvitationOrderField,
    EnterpriseAdministratorRole,
    EnterpriseAllowPrivateRepositoryForkingPolicyValue,
    EnterpriseDefaultRepositoryPermissionSettingValue,
    EnterpriseDisallowedMethodsSettingValue,
    EnterpriseEnabledDisabledSettingValue,
    EnterpriseEnabledSettingValue,
    EnterpriseMemberInvitationOrderField,
    EnterpriseMemberOrderField,
    EnterpriseMembersCanCreateRepositoriesSettingValue,
    EnterpriseMembersCanMakePurchasesSettingValue,
    EnterpriseOrderField,
    EnterpriseServerInstallationOrderField,
    EnterpriseServerUserAccountEmailOrderField,
    EnterpriseServerUserAccountOrderField,
    EnterpriseServerUserAccountsUploadOrderField,
    EnvironmentOrderField,
    GistOrderField,
    IpAllowListEnabledSettingValue,
    IpAllowListEntryOrderField,
    IpAllowListForInstalledAppsEnabledSettingValue,
    IssueClosedStateReason,
    IssueCommentOrderField,
    IssueOrderField,
    IssueState,
    IssueTypeColor,
    IssueTypeOrderField,
    LabelOrderField,
    LanguageOrderField,
    LockReason,
    MannequinOrderField,
    MergeQueueGroupingStrategy,
    MergeQueueMergeMethod,
    MigrationSourceType,
    MilestoneOrderField,
    NotificationRestrictionSettingValue,
    OrderDirection,
    OrganizationMemberRole,
    OrganizationOrderField,
    OrgEnterpriseOwnerOrderField,
    PackageFileOrderField,
    PackageOrderField,
    PackageVersionOrderField,
    PinnedEnvironmentOrderField,
    ProjectOrderField,
    ProjectState,
    ProjectTemplate,
    ProjectV2CustomFieldType,
    ProjectV2FieldOrderField,
    ProjectV2ItemFieldValueOrderField,
    ProjectV2ItemOrderField,
    ProjectV2OrderField,
    ProjectV2Roles,
    ProjectV2SingleSelectFieldOptionColor,
    ProjectV2State,
    ProjectV2StatusUpdateOrderField,
    ProjectV2StatusUpdateStatus,
    ProjectV2ViewOrderField,
    ProjectV2WorkflowsOrderField,
    PullRequestAllowedMergeMethods,
    PullRequestBranchUpdateMethod,
    PullRequestMergeMethod,
    PullRequestOrderField,
    PullRequestReviewEvent,
    PullRequestReviewThreadSubjectType,
    PullRequestUpdateState,
    ReactionContent,
    ReactionOrderField,
    RefOrderField,
    ReleaseOrderField,
    ReportedContentClassifiers,
    RepositoryInteractionLimit,
    RepositoryInteractionLimitExpiry,
    RepositoryInvitationOrderField,
    RepositoryMigrationOrderDirection,
    RepositoryMigrationOrderField,
    RepositoryOrderField,
    RepositoryPermission,
    RepositoryRuleOrderField,
    RepositoryRulesetBypassActorBypassMode,
    RepositoryRulesetTarget,
    RepositoryRuleType,
    RepositoryVisibility,
    RequestableCheckStatusState,
    RoleInOrganization,
    RuleEnforcement,
    SamlDigestAlgorithm,
    SamlSignatureAlgorithm,
    SavedReplyOrderField,
    SecurityAdvisoryIdentifierType,
    SecurityAdvisoryOrderField,
    SecurityVulnerabilityOrderField,
    SponsorableOrderField,
    SponsorAndLifetimeValueOrderField,
    SponsorOrderField,
    SponsorsActivityOrderField,
    SponsorsCountryOrRegionCode,
    SponsorshipNewsletterOrderField,
    SponsorshipOrderField,
    SponsorshipPrivacy,
    SponsorsTierOrderField,
    StarOrderField,
    SubscriptionState,
    TeamDiscussionCommentOrderField,
    TeamDiscussionOrderField,
    TeamMemberOrderField,
    TeamOrderField,
    TeamRepositoryOrderField,
    TeamReviewAssignmentAlgorithm,
    TopicSuggestionDeclineReason,
    UserStatusOrderField,
    VerifiableDomainOrderField,
    WorkflowRunOrderField,
)


class AbortQueuedMigrationsInput(BaseModel):
    clientMutationId: Optional[str] = None
    ownerId: str


class AbortRepositoryMigrationInput(BaseModel):
    clientMutationId: Optional[str] = None
    migrationId: str


class AcceptEnterpriseAdministratorInvitationInput(BaseModel):
    clientMutationId: Optional[str] = None
    invitationId: str


class AcceptEnterpriseMemberInvitationInput(BaseModel):
    clientMutationId: Optional[str] = None
    invitationId: str


class AcceptTopicSuggestionInput(BaseModel):
    clientMutationId: Optional[str] = None
    name: Optional[str] = None
    repositoryId: Optional[str] = None


class AccessUserNamespaceRepositoryInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    repositoryId: str


class AddAssigneesToAssignableInput(BaseModel):
    assignableId: str
    assigneeIds: List[str]
    clientMutationId: Optional[str] = None


class AddCommentInput(BaseModel):
    body: str
    clientMutationId: Optional[str] = None
    subjectId: str


class AddDiscussionCommentInput(BaseModel):
    body: str
    clientMutationId: Optional[str] = None
    discussionId: str
    replyToId: Optional[str] = None


class AddDiscussionPollVoteInput(BaseModel):
    clientMutationId: Optional[str] = None
    pollOptionId: str


class AddEnterpriseOrganizationMemberInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    organizationId: str
    role: Optional[OrganizationMemberRole] = None
    userIds: List[str]


class AddEnterpriseSupportEntitlementInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    login: str


class AddLabelsToLabelableInput(BaseModel):
    clientMutationId: Optional[str] = None
    labelIds: List[str]
    labelableId: str


class AddProjectCardInput(BaseModel):
    clientMutationId: Optional[str] = None
    contentId: Optional[str] = None
    note: Optional[str] = None
    projectColumnId: str


class AddProjectColumnInput(BaseModel):
    clientMutationId: Optional[str] = None
    name: str
    projectId: str


class AddProjectV2DraftIssueInput(BaseModel):
    assigneeIds: Optional[List[str]] = None
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    projectId: str
    title: str


class AddProjectV2ItemByIdInput(BaseModel):
    clientMutationId: Optional[str] = None
    contentId: str
    projectId: str


class AddPullRequestReviewCommentInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    commitOID: Optional[Any] = None
    inReplyTo: Optional[str] = None
    path: Optional[str] = None
    position: Optional[int] = None
    pullRequestId: Optional[str] = None
    pullRequestReviewId: Optional[str] = None


class AddPullRequestReviewInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    comments: Optional[List[Optional["DraftPullRequestReviewComment"]]] = None
    commitOID: Optional[Any] = None
    event: Optional[PullRequestReviewEvent] = None
    pullRequestId: str
    threads: Optional[List[Optional["DraftPullRequestReviewThread"]]] = None


class AddPullRequestReviewThreadInput(BaseModel):
    body: str
    clientMutationId: Optional[str] = None
    line: Optional[int] = None
    path: Optional[str] = None
    pullRequestId: Optional[str] = None
    pullRequestReviewId: Optional[str] = None
    side: Optional[DiffSide] = DiffSide.RIGHT
    startLine: Optional[int] = None
    startSide: Optional[DiffSide] = DiffSide.RIGHT
    subjectType: Optional[PullRequestReviewThreadSubjectType] = (
        PullRequestReviewThreadSubjectType.LINE
    )


class AddPullRequestReviewThreadReplyInput(BaseModel):
    body: str
    clientMutationId: Optional[str] = None
    pullRequestReviewId: Optional[str] = None
    pullRequestReviewThreadId: str


class AddReactionInput(BaseModel):
    clientMutationId: Optional[str] = None
    content: ReactionContent
    subjectId: str


class AddStarInput(BaseModel):
    clientMutationId: Optional[str] = None
    starrableId: str


class AddSubIssueInput(BaseModel):
    clientMutationId: Optional[str] = None
    issueId: str
    replaceParent: Optional[bool] = None
    subIssueId: Optional[str] = None
    subIssueUrl: Optional[str] = None


class AddUpvoteInput(BaseModel):
    clientMutationId: Optional[str] = None
    subjectId: str


class AddVerifiableDomainInput(BaseModel):
    clientMutationId: Optional[str] = None
    domain: Any
    ownerId: str


class ApproveDeploymentsInput(BaseModel):
    clientMutationId: Optional[str] = None
    comment: Optional[str] = ""
    environmentIds: List[str]
    workflowRunId: str


class ApproveVerifiableDomainInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class ArchiveProjectV2ItemInput(BaseModel):
    clientMutationId: Optional[str] = None
    itemId: str
    projectId: str


class ArchiveRepositoryInput(BaseModel):
    clientMutationId: Optional[str] = None
    repositoryId: str


class AuditLogOrder(BaseModel):
    direction: Optional[OrderDirection] = None
    field: Optional[AuditLogOrderField] = None


class BranchNamePatternParametersInput(BaseModel):
    name: Optional[str] = None
    negate: Optional[bool] = None
    operator: str
    pattern: str


class BulkSponsorship(BaseModel):
    amount: int
    sponsorableId: Optional[str] = None
    sponsorableLogin: Optional[str] = None


class CancelEnterpriseAdminInvitationInput(BaseModel):
    clientMutationId: Optional[str] = None
    invitationId: str


class CancelEnterpriseMemberInvitationInput(BaseModel):
    clientMutationId: Optional[str] = None
    invitationId: str


class CancelSponsorshipInput(BaseModel):
    clientMutationId: Optional[str] = None
    sponsorId: Optional[str] = None
    sponsorLogin: Optional[str] = None
    sponsorableId: Optional[str] = None
    sponsorableLogin: Optional[str] = None


class ChangeUserStatusInput(BaseModel):
    clientMutationId: Optional[str] = None
    emoji: Optional[str] = None
    expiresAt: Optional[Any] = None
    limitedAvailability: Optional[bool] = False
    message: Optional[str] = None
    organizationId: Optional[str] = None


class CheckAnnotationData(BaseModel):
    annotationLevel: CheckAnnotationLevel
    location: "CheckAnnotationRange"
    message: str
    path: str
    rawDetails: Optional[str] = None
    title: Optional[str] = None


class CheckAnnotationRange(BaseModel):
    endColumn: Optional[int] = None
    endLine: int
    startColumn: Optional[int] = None
    startLine: int


class CheckRunAction(BaseModel):
    description: str
    identifier: str
    label: str


class CheckRunFilter(BaseModel):
    appId: Optional[int] = None
    checkName: Optional[str] = None
    checkType: Optional[CheckRunType] = None
    conclusions: Optional[List[CheckConclusionState]] = None
    status: Optional[CheckStatusState] = None
    statuses: Optional[List[CheckStatusState]] = None


class CheckRunOutput(BaseModel):
    annotations: Optional[List["CheckAnnotationData"]] = None
    images: Optional[List["CheckRunOutputImage"]] = None
    summary: str
    text: Optional[str] = None
    title: str


class CheckRunOutputImage(BaseModel):
    alt: str
    caption: Optional[str] = None
    imageUrl: Any


class CheckSuiteAutoTriggerPreference(BaseModel):
    appId: str
    setting: bool


class CheckSuiteFilter(BaseModel):
    appId: Optional[int] = None
    checkName: Optional[str] = None


class ClearLabelsFromLabelableInput(BaseModel):
    clientMutationId: Optional[str] = None
    labelableId: str


class ClearProjectV2ItemFieldValueInput(BaseModel):
    clientMutationId: Optional[str] = None
    fieldId: str
    itemId: str
    projectId: str


class CloneProjectInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    includeWorkflows: bool
    name: str
    public: Optional[bool] = None
    sourceId: str
    targetOwnerId: str


class CloneTemplateRepositoryInput(BaseModel):
    clientMutationId: Optional[str] = None
    description: Optional[str] = None
    includeAllBranches: Optional[bool] = False
    name: str
    ownerId: str
    repositoryId: str
    visibility: RepositoryVisibility


class CloseDiscussionInput(BaseModel):
    clientMutationId: Optional[str] = None
    discussionId: str
    reason: Optional[DiscussionCloseReason] = DiscussionCloseReason.RESOLVED


class CloseIssueInput(BaseModel):
    clientMutationId: Optional[str] = None
    duplicateIssueId: Optional[str] = None
    issueId: str
    stateReason: Optional[IssueClosedStateReason] = None


class ClosePullRequestInput(BaseModel):
    clientMutationId: Optional[str] = None
    pullRequestId: str


class CodeScanningParametersInput(BaseModel):
    codeScanningTools: List["CodeScanningToolInput"]


class CodeScanningToolInput(BaseModel):
    alertsThreshold: str
    securityAlertsThreshold: str
    tool: str


class CommitAuthor(BaseModel):
    emails: Optional[List[str]] = None
    id: Optional[str] = None


class CommitAuthorEmailPatternParametersInput(BaseModel):
    name: Optional[str] = None
    negate: Optional[bool] = None
    operator: str
    pattern: str


class CommitContributionOrder(BaseModel):
    direction: OrderDirection
    field: CommitContributionOrderField


class CommitMessage(BaseModel):
    body: Optional[str] = None
    headline: str


class CommitMessagePatternParametersInput(BaseModel):
    name: Optional[str] = None
    negate: Optional[bool] = None
    operator: str
    pattern: str


class CommittableBranch(BaseModel):
    branchName: Optional[str] = None
    id: Optional[str] = None
    repositoryNameWithOwner: Optional[str] = None


class CommitterEmailPatternParametersInput(BaseModel):
    name: Optional[str] = None
    negate: Optional[bool] = None
    operator: str
    pattern: str


class ContributionOrder(BaseModel):
    direction: OrderDirection


class ConvertProjectCardNoteToIssueInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    projectCardId: str
    repositoryId: str
    title: Optional[str] = None


class ConvertProjectV2DraftIssueItemToIssueInput(BaseModel):
    clientMutationId: Optional[str] = None
    itemId: str
    repositoryId: str


class ConvertPullRequestToDraftInput(BaseModel):
    clientMutationId: Optional[str] = None
    pullRequestId: str


class CopyProjectV2Input(BaseModel):
    clientMutationId: Optional[str] = None
    includeDraftIssues: Optional[bool] = False
    ownerId: str
    projectId: str
    title: str


class CreateAttributionInvitationInput(BaseModel):
    clientMutationId: Optional[str] = None
    ownerId: str
    sourceId: str
    targetId: str


class CreateBranchProtectionRuleInput(BaseModel):
    allowsDeletions: Optional[bool] = None
    allowsForcePushes: Optional[bool] = None
    blocksCreations: Optional[bool] = None
    bypassForcePushActorIds: Optional[List[str]] = None
    bypassPullRequestActorIds: Optional[List[str]] = None
    clientMutationId: Optional[str] = None
    dismissesStaleReviews: Optional[bool] = None
    isAdminEnforced: Optional[bool] = None
    lockAllowsFetchAndMerge: Optional[bool] = None
    lockBranch: Optional[bool] = None
    pattern: str
    pushActorIds: Optional[List[str]] = None
    repositoryId: str
    requireLastPushApproval: Optional[bool] = None
    requiredApprovingReviewCount: Optional[int] = None
    requiredDeploymentEnvironments: Optional[List[str]] = None
    requiredStatusCheckContexts: Optional[List[str]] = None
    requiredStatusChecks: Optional[List["RequiredStatusCheckInput"]] = None
    requiresApprovingReviews: Optional[bool] = None
    requiresCodeOwnerReviews: Optional[bool] = None
    requiresCommitSignatures: Optional[bool] = None
    requiresConversationResolution: Optional[bool] = None
    requiresDeployments: Optional[bool] = None
    requiresLinearHistory: Optional[bool] = None
    requiresStatusChecks: Optional[bool] = None
    requiresStrictStatusChecks: Optional[bool] = None
    restrictsPushes: Optional[bool] = None
    restrictsReviewDismissals: Optional[bool] = None
    reviewDismissalActorIds: Optional[List[str]] = None


class CreateCheckRunInput(BaseModel):
    actions: Optional[List["CheckRunAction"]] = None
    clientMutationId: Optional[str] = None
    completedAt: Optional[Any] = None
    conclusion: Optional[CheckConclusionState] = None
    detailsUrl: Optional[Any] = None
    externalId: Optional[str] = None
    headSha: Any
    name: str
    output: Optional["CheckRunOutput"] = None
    repositoryId: str
    startedAt: Optional[Any] = None
    status: Optional[RequestableCheckStatusState] = None


class CreateCheckSuiteInput(BaseModel):
    clientMutationId: Optional[str] = None
    headSha: Any
    repositoryId: str


class CreateCommitOnBranchInput(BaseModel):
    branch: "CommittableBranch"
    clientMutationId: Optional[str] = None
    expectedHeadOid: Any
    fileChanges: Optional["FileChanges"] = None
    message: "CommitMessage"


class CreateDeploymentInput(BaseModel):
    autoMerge: Optional[bool] = True
    clientMutationId: Optional[str] = None
    description: Optional[str] = ""
    environment: Optional[str] = "production"
    payload: Optional[str] = "{}"
    refId: str
    repositoryId: str
    requiredContexts: Optional[List[str]] = None
    task: Optional[str] = "deploy"


class CreateDeploymentStatusInput(BaseModel):
    autoInactive: Optional[bool] = True
    clientMutationId: Optional[str] = None
    deploymentId: str
    description: Optional[str] = ""
    environment: Optional[str] = None
    environmentUrl: Optional[str] = ""
    logUrl: Optional[str] = ""
    state: DeploymentStatusState


class CreateDiscussionInput(BaseModel):
    body: str
    categoryId: str
    clientMutationId: Optional[str] = None
    repositoryId: str
    title: str


class CreateEnterpriseOrganizationInput(BaseModel):
    adminLogins: List[str]
    billingEmail: str
    clientMutationId: Optional[str] = None
    enterpriseId: str
    login: str
    profileName: str


class CreateEnvironmentInput(BaseModel):
    clientMutationId: Optional[str] = None
    name: str
    repositoryId: str


class CreateIpAllowListEntryInput(BaseModel):
    allowListValue: str
    clientMutationId: Optional[str] = None
    isActive: bool
    name: Optional[str] = None
    ownerId: str


class CreateIssueInput(BaseModel):
    assigneeIds: Optional[List[str]] = None
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    issueTemplate: Optional[str] = None
    issueTypeId: Optional[str] = None
    labelIds: Optional[List[str]] = None
    milestoneId: Optional[str] = None
    parentIssueId: Optional[str] = None
    projectIds: Optional[List[str]] = None
    repositoryId: str
    title: str


class CreateIssueTypeInput(BaseModel):
    clientMutationId: Optional[str] = None
    color: Optional[IssueTypeColor] = None
    description: Optional[str] = None
    isEnabled: bool
    name: str
    ownerId: str


class CreateLabelInput(BaseModel):
    clientMutationId: Optional[str] = None
    color: str
    description: Optional[str] = None
    name: str
    repositoryId: str


class CreateLinkedBranchInput(BaseModel):
    clientMutationId: Optional[str] = None
    issueId: str
    name: Optional[str] = None
    oid: Any
    repositoryId: Optional[str] = None


class CreateMigrationSourceInput(BaseModel):
    accessToken: Optional[str] = None
    clientMutationId: Optional[str] = None
    githubPat: Optional[str] = None
    name: str
    ownerId: str
    type: MigrationSourceType
    url: Optional[str] = None


class CreateProjectInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    name: str
    ownerId: str
    repositoryIds: Optional[List[str]] = None
    template: Optional[ProjectTemplate] = None


class CreateProjectV2FieldInput(BaseModel):
    clientMutationId: Optional[str] = None
    dataType: ProjectV2CustomFieldType
    iterationConfiguration: Optional["ProjectV2IterationFieldConfigurationInput"] = None
    name: str
    projectId: str
    singleSelectOptions: Optional[List["ProjectV2SingleSelectFieldOptionInput"]] = None


class CreateProjectV2Input(BaseModel):
    clientMutationId: Optional[str] = None
    ownerId: str
    repositoryId: Optional[str] = None
    teamId: Optional[str] = None
    title: str


class CreateProjectV2StatusUpdateInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    projectId: str
    startDate: Optional[Any] = None
    status: Optional[ProjectV2StatusUpdateStatus] = None
    targetDate: Optional[Any] = None


class CreatePullRequestInput(BaseModel):
    baseRefName: str
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    draft: Optional[bool] = False
    headRefName: str
    headRepositoryId: Optional[str] = None
    maintainerCanModify: Optional[bool] = True
    repositoryId: str
    title: str


class CreateRefInput(BaseModel):
    clientMutationId: Optional[str] = None
    name: str
    oid: Any
    repositoryId: str


class CreateRepositoryInput(BaseModel):
    clientMutationId: Optional[str] = None
    description: Optional[str] = None
    hasIssuesEnabled: Optional[bool] = True
    hasWikiEnabled: Optional[bool] = False
    homepageUrl: Optional[Any] = None
    name: str
    ownerId: Optional[str] = None
    teamId: Optional[str] = None
    template: Optional[bool] = False
    visibility: RepositoryVisibility


class CreateRepositoryRulesetInput(BaseModel):
    bypassActors: Optional[List["RepositoryRulesetBypassActorInput"]] = None
    clientMutationId: Optional[str] = None
    conditions: "RepositoryRuleConditionsInput"
    enforcement: RuleEnforcement
    name: str
    rules: Optional[List["RepositoryRuleInput"]] = None
    sourceId: str
    target: Optional[RepositoryRulesetTarget] = None


class CreateSponsorsListingInput(BaseModel):
    billingCountryOrRegionCode: Optional[SponsorsCountryOrRegionCode] = None
    clientMutationId: Optional[str] = None
    contactEmail: Optional[str] = None
    fiscalHostLogin: Optional[str] = None
    fiscallyHostedProjectProfileUrl: Optional[str] = None
    fullDescription: Optional[str] = None
    residenceCountryOrRegionCode: Optional[SponsorsCountryOrRegionCode] = None
    sponsorableLogin: Optional[str] = None


class CreateSponsorsTierInput(BaseModel):
    amount: int
    clientMutationId: Optional[str] = None
    description: str
    isRecurring: Optional[bool] = True
    publish: Optional[bool] = False
    repositoryId: Optional[str] = None
    repositoryName: Optional[str] = None
    repositoryOwnerLogin: Optional[str] = None
    sponsorableId: Optional[str] = None
    sponsorableLogin: Optional[str] = None
    welcomeMessage: Optional[str] = None


class CreateSponsorshipInput(BaseModel):
    amount: Optional[int] = None
    clientMutationId: Optional[str] = None
    isRecurring: Optional[bool] = None
    privacyLevel: Optional[SponsorshipPrivacy] = SponsorshipPrivacy.PUBLIC
    receiveEmails: Optional[bool] = True
    sponsorId: Optional[str] = None
    sponsorLogin: Optional[str] = None
    sponsorableId: Optional[str] = None
    sponsorableLogin: Optional[str] = None
    tierId: Optional[str] = None


class CreateSponsorshipsInput(BaseModel):
    clientMutationId: Optional[str] = None
    privacyLevel: Optional[SponsorshipPrivacy] = SponsorshipPrivacy.PUBLIC
    receiveEmails: Optional[bool] = False
    recurring: Optional[bool] = False
    sponsorLogin: str
    sponsorships: List["BulkSponsorship"]


class CreateTeamDiscussionCommentInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    discussionId: Optional[str] = None


class CreateTeamDiscussionInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    private: Optional[bool] = None
    teamId: Optional[str] = None
    title: Optional[str] = None


class CreateUserListInput(BaseModel):
    clientMutationId: Optional[str] = None
    description: Optional[str] = None
    isPrivate: Optional[bool] = False
    name: str


class DeclineTopicSuggestionInput(BaseModel):
    clientMutationId: Optional[str] = None
    name: Optional[str] = None
    reason: Optional[TopicSuggestionDeclineReason] = None
    repositoryId: Optional[str] = None


class DeleteBranchProtectionRuleInput(BaseModel):
    branchProtectionRuleId: str
    clientMutationId: Optional[str] = None


class DeleteDeploymentInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DeleteDiscussionCommentInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DeleteDiscussionInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DeleteEnvironmentInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DeleteIpAllowListEntryInput(BaseModel):
    clientMutationId: Optional[str] = None
    ipAllowListEntryId: str


class DeleteIssueCommentInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DeleteIssueInput(BaseModel):
    clientMutationId: Optional[str] = None
    issueId: str


class DeleteIssueTypeInput(BaseModel):
    clientMutationId: Optional[str] = None
    issueTypeId: str


class DeleteLabelInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DeleteLinkedBranchInput(BaseModel):
    clientMutationId: Optional[str] = None
    linkedBranchId: str


class DeletePackageVersionInput(BaseModel):
    clientMutationId: Optional[str] = None
    packageVersionId: str


class DeleteProjectCardInput(BaseModel):
    cardId: str
    clientMutationId: Optional[str] = None


class DeleteProjectColumnInput(BaseModel):
    clientMutationId: Optional[str] = None
    columnId: str


class DeleteProjectInput(BaseModel):
    clientMutationId: Optional[str] = None
    projectId: str


class DeleteProjectV2FieldInput(BaseModel):
    clientMutationId: Optional[str] = None
    fieldId: str


class DeleteProjectV2Input(BaseModel):
    clientMutationId: Optional[str] = None
    projectId: str


class DeleteProjectV2ItemInput(BaseModel):
    clientMutationId: Optional[str] = None
    itemId: str
    projectId: str


class DeleteProjectV2StatusUpdateInput(BaseModel):
    clientMutationId: Optional[str] = None
    statusUpdateId: str


class DeleteProjectV2WorkflowInput(BaseModel):
    clientMutationId: Optional[str] = None
    workflowId: str


class DeletePullRequestReviewCommentInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DeletePullRequestReviewInput(BaseModel):
    clientMutationId: Optional[str] = None
    pullRequestReviewId: str


class DeleteRefInput(BaseModel):
    clientMutationId: Optional[str] = None
    refId: str


class DeleteRepositoryRulesetInput(BaseModel):
    clientMutationId: Optional[str] = None
    repositoryRulesetId: str


class DeleteTeamDiscussionCommentInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DeleteTeamDiscussionInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DeleteUserListInput(BaseModel):
    clientMutationId: Optional[str] = None
    listId: str


class DeleteVerifiableDomainInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DeploymentOrder(BaseModel):
    direction: OrderDirection
    field: DeploymentOrderField


class DequeuePullRequestInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class DisablePullRequestAutoMergeInput(BaseModel):
    clientMutationId: Optional[str] = None
    pullRequestId: str


class DiscussionOrder(BaseModel):
    direction: OrderDirection
    field: DiscussionOrderField


class DiscussionPollOptionOrder(BaseModel):
    direction: OrderDirection
    field: DiscussionPollOptionOrderField


class DismissPullRequestReviewInput(BaseModel):
    clientMutationId: Optional[str] = None
    message: str
    pullRequestReviewId: str


class DismissRepositoryVulnerabilityAlertInput(BaseModel):
    clientMutationId: Optional[str] = None
    dismissReason: DismissReason
    repositoryVulnerabilityAlertId: str


class DraftPullRequestReviewComment(BaseModel):
    body: str
    path: str
    position: int


class DraftPullRequestReviewThread(BaseModel):
    body: str
    line: Optional[int] = None
    path: Optional[str] = None
    side: Optional[DiffSide] = DiffSide.RIGHT
    startLine: Optional[int] = None
    startSide: Optional[DiffSide] = DiffSide.RIGHT


class EnablePullRequestAutoMergeInput(BaseModel):
    authorEmail: Optional[str] = None
    clientMutationId: Optional[str] = None
    commitBody: Optional[str] = None
    commitHeadline: Optional[str] = None
    expectedHeadOid: Optional[Any] = None
    mergeMethod: Optional[PullRequestMergeMethod] = PullRequestMergeMethod.MERGE
    pullRequestId: str


class EnqueuePullRequestInput(BaseModel):
    clientMutationId: Optional[str] = None
    expectedHeadOid: Optional[Any] = None
    jump: Optional[bool] = None
    pullRequestId: str


class EnterpriseAdministratorInvitationOrder(BaseModel):
    direction: OrderDirection
    field: EnterpriseAdministratorInvitationOrderField


class EnterpriseMemberInvitationOrder(BaseModel):
    direction: OrderDirection
    field: EnterpriseMemberInvitationOrderField


class EnterpriseMemberOrder(BaseModel):
    direction: OrderDirection
    field: EnterpriseMemberOrderField


class EnterpriseOrder(BaseModel):
    direction: OrderDirection
    field: EnterpriseOrderField


class EnterpriseServerInstallationOrder(BaseModel):
    direction: OrderDirection
    field: EnterpriseServerInstallationOrderField


class EnterpriseServerUserAccountEmailOrder(BaseModel):
    direction: OrderDirection
    field: EnterpriseServerUserAccountEmailOrderField


class EnterpriseServerUserAccountOrder(BaseModel):
    direction: OrderDirection
    field: EnterpriseServerUserAccountOrderField


class EnterpriseServerUserAccountsUploadOrder(BaseModel):
    direction: OrderDirection
    field: EnterpriseServerUserAccountsUploadOrderField


class Environments(BaseModel):
    direction: OrderDirection
    field: EnvironmentOrderField


class FileAddition(BaseModel):
    contents: Any
    path: str


class FileChanges(BaseModel):
    additions: Optional[List["FileAddition"]] = Field(default_factory=lambda: [])
    deletions: Optional[List["FileDeletion"]] = Field(default_factory=lambda: [])


class FileDeletion(BaseModel):
    path: str


class FileExtensionRestrictionParametersInput(BaseModel):
    restrictedFileExtensions: List[str]


class FilePathRestrictionParametersInput(BaseModel):
    restrictedFilePaths: List[str]


class FollowOrganizationInput(BaseModel):
    clientMutationId: Optional[str] = None
    organizationId: str


class FollowUserInput(BaseModel):
    clientMutationId: Optional[str] = None
    userId: str


class GistOrder(BaseModel):
    direction: OrderDirection
    field: GistOrderField


class GrantEnterpriseOrganizationsMigratorRoleInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    login: str


class GrantMigratorRoleInput(BaseModel):
    actor: str
    actorType: ActorType
    clientMutationId: Optional[str] = None
    organizationId: str


class ImportProjectInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    columnImports: List["ProjectColumnImport"]
    name: str
    ownerName: str
    public: Optional[bool] = False


class InviteEnterpriseAdminInput(BaseModel):
    clientMutationId: Optional[str] = None
    email: Optional[str] = None
    enterpriseId: str
    invitee: Optional[str] = None
    role: Optional[EnterpriseAdministratorRole] = None


class InviteEnterpriseMemberInput(BaseModel):
    clientMutationId: Optional[str] = None
    email: Optional[str] = None
    enterpriseId: str
    invitee: Optional[str] = None


class IpAllowListEntryOrder(BaseModel):
    direction: OrderDirection
    field: IpAllowListEntryOrderField


class IssueCommentOrder(BaseModel):
    direction: OrderDirection
    field: IssueCommentOrderField


class IssueFilters(BaseModel):
    assignee: Optional[str] = None
    createdBy: Optional[str] = None
    labels: Optional[List[str]] = None
    mentioned: Optional[str] = None
    milestone: Optional[str] = None
    milestoneNumber: Optional[str] = None
    since: Optional[Any] = None
    states: Optional[List[IssueState]] = None
    type: Optional[str] = None
    viewerSubscribed: Optional[bool] = False


class IssueOrder(BaseModel):
    direction: OrderDirection
    field: IssueOrderField


class IssueTypeOrder(BaseModel):
    direction: OrderDirection
    field: IssueTypeOrderField


class LabelOrder(BaseModel):
    direction: OrderDirection
    field: LabelOrderField


class LanguageOrder(BaseModel):
    direction: OrderDirection
    field: LanguageOrderField


class LinkProjectV2ToRepositoryInput(BaseModel):
    clientMutationId: Optional[str] = None
    projectId: str
    repositoryId: str


class LinkProjectV2ToTeamInput(BaseModel):
    clientMutationId: Optional[str] = None
    projectId: str
    teamId: str


class LinkRepositoryToProjectInput(BaseModel):
    clientMutationId: Optional[str] = None
    projectId: str
    repositoryId: str


class LockLockableInput(BaseModel):
    clientMutationId: Optional[str] = None
    lockReason: Optional[LockReason] = None
    lockableId: str


class MannequinOrder(BaseModel):
    direction: OrderDirection
    field: MannequinOrderField


class MarkDiscussionCommentAsAnswerInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class MarkFileAsViewedInput(BaseModel):
    clientMutationId: Optional[str] = None
    path: str
    pullRequestId: str


class MarkProjectV2AsTemplateInput(BaseModel):
    clientMutationId: Optional[str] = None
    projectId: str


class MarkPullRequestReadyForReviewInput(BaseModel):
    clientMutationId: Optional[str] = None
    pullRequestId: str


class MaxFilePathLengthParametersInput(BaseModel):
    maxFilePathLength: int


class MaxFileSizeParametersInput(BaseModel):
    maxFileSize: int


class MergeBranchInput(BaseModel):
    authorEmail: Optional[str] = None
    base: str
    clientMutationId: Optional[str] = None
    commitMessage: Optional[str] = None
    head: str
    repositoryId: str


class MergePullRequestInput(BaseModel):
    authorEmail: Optional[str] = None
    clientMutationId: Optional[str] = None
    commitBody: Optional[str] = None
    commitHeadline: Optional[str] = None
    expectedHeadOid: Optional[Any] = None
    mergeMethod: Optional[PullRequestMergeMethod] = PullRequestMergeMethod.MERGE
    pullRequestId: str


class MergeQueueParametersInput(BaseModel):
    checkResponseTimeoutMinutes: int
    groupingStrategy: MergeQueueGroupingStrategy
    maxEntriesToBuild: int
    maxEntriesToMerge: int
    mergeMethod: MergeQueueMergeMethod
    minEntriesToMerge: int
    minEntriesToMergeWaitMinutes: int


class MilestoneOrder(BaseModel):
    direction: OrderDirection
    field: MilestoneOrderField


class MinimizeCommentInput(BaseModel):
    classifier: ReportedContentClassifiers
    clientMutationId: Optional[str] = None
    subjectId: str


class MoveProjectCardInput(BaseModel):
    afterCardId: Optional[str] = None
    cardId: str
    clientMutationId: Optional[str] = None
    columnId: str


class MoveProjectColumnInput(BaseModel):
    afterColumnId: Optional[str] = None
    clientMutationId: Optional[str] = None
    columnId: str


class OrgEnterpriseOwnerOrder(BaseModel):
    direction: OrderDirection
    field: OrgEnterpriseOwnerOrderField


class OrganizationOrder(BaseModel):
    direction: OrderDirection
    field: OrganizationOrderField


class PackageFileOrder(BaseModel):
    direction: Optional[OrderDirection] = None
    field: Optional[PackageFileOrderField] = None


class PackageOrder(BaseModel):
    direction: Optional[OrderDirection] = None
    field: Optional[PackageOrderField] = None


class PackageVersionOrder(BaseModel):
    direction: Optional[OrderDirection] = None
    field: Optional[PackageVersionOrderField] = None


class PinEnvironmentInput(BaseModel):
    clientMutationId: Optional[str] = None
    environmentId: str
    pinned: bool


class PinIssueInput(BaseModel):
    clientMutationId: Optional[str] = None
    issueId: str


class PinnedEnvironmentOrder(BaseModel):
    direction: OrderDirection
    field: PinnedEnvironmentOrderField


class ProjectCardImport(BaseModel):
    number: int
    repository: str


class ProjectColumnImport(BaseModel):
    columnName: str
    issues: Optional[List["ProjectCardImport"]] = None
    position: int


class ProjectOrder(BaseModel):
    direction: OrderDirection
    field: ProjectOrderField


class ProjectV2Collaborator(BaseModel):
    role: ProjectV2Roles
    teamId: Optional[str] = None
    userId: Optional[str] = None


class ProjectV2FieldOrder(BaseModel):
    direction: OrderDirection
    field: ProjectV2FieldOrderField


class ProjectV2FieldValue(BaseModel):
    date: Optional[Any] = None
    iterationId: Optional[str] = None
    number: Optional[float] = None
    singleSelectOptionId: Optional[str] = None
    text: Optional[str] = None


class ProjectV2Filters(BaseModel):
    state: Optional[ProjectV2State] = None


class ProjectV2ItemFieldValueOrder(BaseModel):
    direction: OrderDirection
    field: ProjectV2ItemFieldValueOrderField


class ProjectV2ItemOrder(BaseModel):
    direction: OrderDirection
    field: ProjectV2ItemOrderField


class ProjectV2Iteration(BaseModel):
    duration: int
    startDate: Any
    title: str


class ProjectV2IterationFieldConfigurationInput(BaseModel):
    duration: int
    iterations: List["ProjectV2Iteration"]
    startDate: Any


class ProjectV2Order(BaseModel):
    direction: OrderDirection
    field: ProjectV2OrderField


class ProjectV2SingleSelectFieldOptionInput(BaseModel):
    color: ProjectV2SingleSelectFieldOptionColor
    description: str
    name: str


class ProjectV2StatusOrder(BaseModel):
    direction: OrderDirection
    field: ProjectV2StatusUpdateOrderField


class ProjectV2ViewOrder(BaseModel):
    direction: OrderDirection
    field: ProjectV2ViewOrderField


class ProjectV2WorkflowOrder(BaseModel):
    direction: OrderDirection
    field: ProjectV2WorkflowsOrderField


class PropertyTargetDefinitionInput(BaseModel):
    name: str
    propertyValues: List[str]
    source: Optional[str] = None


class PublishSponsorsTierInput(BaseModel):
    clientMutationId: Optional[str] = None
    tierId: str


class PullRequestOrder(BaseModel):
    direction: OrderDirection
    field: PullRequestOrderField


class PullRequestParametersInput(BaseModel):
    allowedMergeMethods: Optional[List[PullRequestAllowedMergeMethods]] = None
    automaticCopilotCodeReviewEnabled: Optional[bool] = None
    dismissStaleReviewsOnPush: bool
    requireCodeOwnerReview: bool
    requireLastPushApproval: bool
    requiredApprovingReviewCount: int
    requiredReviewThreadResolution: bool


class ReactionOrder(BaseModel):
    direction: OrderDirection
    field: ReactionOrderField


class RefNameConditionTargetInput(BaseModel):
    exclude: List[str]
    include: List[str]


class RefOrder(BaseModel):
    direction: OrderDirection
    field: RefOrderField


class RefUpdate(BaseModel):
    afterOid: Any
    beforeOid: Optional[Any] = None
    force: Optional[bool] = False
    name: Any


class RegenerateEnterpriseIdentityProviderRecoveryCodesInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str


class RegenerateVerifiableDomainTokenInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class RejectDeploymentsInput(BaseModel):
    clientMutationId: Optional[str] = None
    comment: Optional[str] = ""
    environmentIds: List[str]
    workflowRunId: str


class ReleaseOrder(BaseModel):
    direction: OrderDirection
    field: ReleaseOrderField


class RemoveAssigneesFromAssignableInput(BaseModel):
    assignableId: str
    assigneeIds: List[str]
    clientMutationId: Optional[str] = None


class RemoveEnterpriseAdminInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    login: str


class RemoveEnterpriseIdentityProviderInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str


class RemoveEnterpriseMemberInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    userId: str


class RemoveEnterpriseOrganizationInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    organizationId: str


class RemoveEnterpriseSupportEntitlementInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    login: str


class RemoveLabelsFromLabelableInput(BaseModel):
    clientMutationId: Optional[str] = None
    labelIds: List[str]
    labelableId: str


class RemoveOutsideCollaboratorInput(BaseModel):
    clientMutationId: Optional[str] = None
    organizationId: str
    userId: str


class RemoveReactionInput(BaseModel):
    clientMutationId: Optional[str] = None
    content: ReactionContent
    subjectId: str


class RemoveStarInput(BaseModel):
    clientMutationId: Optional[str] = None
    starrableId: str


class RemoveSubIssueInput(BaseModel):
    clientMutationId: Optional[str] = None
    issueId: str
    subIssueId: str


class RemoveUpvoteInput(BaseModel):
    clientMutationId: Optional[str] = None
    subjectId: str


class ReopenDiscussionInput(BaseModel):
    clientMutationId: Optional[str] = None
    discussionId: str


class ReopenIssueInput(BaseModel):
    clientMutationId: Optional[str] = None
    issueId: str


class ReopenPullRequestInput(BaseModel):
    clientMutationId: Optional[str] = None
    pullRequestId: str


class ReorderEnvironmentInput(BaseModel):
    clientMutationId: Optional[str] = None
    environmentId: str
    position: int


class ReplaceActorsForAssignableInput(BaseModel):
    actorIds: List[str]
    assignableId: str
    clientMutationId: Optional[str] = None


class RepositoryIdConditionTargetInput(BaseModel):
    repositoryIds: List[str]


class RepositoryInvitationOrder(BaseModel):
    direction: OrderDirection
    field: RepositoryInvitationOrderField


class RepositoryMigrationOrder(BaseModel):
    direction: RepositoryMigrationOrderDirection
    field: RepositoryMigrationOrderField


class RepositoryNameConditionTargetInput(BaseModel):
    exclude: List[str]
    include: List[str]
    protected: Optional[bool] = None


class RepositoryOrder(BaseModel):
    direction: OrderDirection
    field: RepositoryOrderField


class RepositoryPropertyConditionTargetInput(BaseModel):
    exclude: List["PropertyTargetDefinitionInput"]
    include: List["PropertyTargetDefinitionInput"]


class RepositoryRuleConditionsInput(BaseModel):
    refName: Optional["RefNameConditionTargetInput"] = None
    repositoryId: Optional["RepositoryIdConditionTargetInput"] = None
    repositoryName: Optional["RepositoryNameConditionTargetInput"] = None
    repositoryProperty: Optional["RepositoryPropertyConditionTargetInput"] = None


class RepositoryRuleInput(BaseModel):
    id: Optional[str] = None
    parameters: Optional["RuleParametersInput"] = None
    type: RepositoryRuleType


class RepositoryRuleOrder(BaseModel):
    direction: OrderDirection
    field: RepositoryRuleOrderField


class RepositoryRulesetBypassActorInput(BaseModel):
    actorId: Optional[str] = None
    bypassMode: RepositoryRulesetBypassActorBypassMode
    deployKey: Optional[bool] = None
    enterpriseOwner: Optional[bool] = None
    organizationAdmin: Optional[bool] = None
    repositoryRoleDatabaseId: Optional[int] = None


class ReprioritizeSubIssueInput(BaseModel):
    afterId: Optional[str] = None
    beforeId: Optional[str] = None
    clientMutationId: Optional[str] = None
    issueId: str
    subIssueId: str


class RequestReviewsInput(BaseModel):
    botIds: Optional[List[str]] = None
    clientMutationId: Optional[str] = None
    pullRequestId: str
    teamIds: Optional[List[str]] = None
    union: Optional[bool] = False
    userIds: Optional[List[str]] = None


class RequiredDeploymentsParametersInput(BaseModel):
    requiredDeploymentEnvironments: List[str]


class RequiredStatusCheckInput(BaseModel):
    appId: Optional[str] = None
    context: str


class RequiredStatusChecksParametersInput(BaseModel):
    doNotEnforceOnCreate: Optional[bool] = None
    requiredStatusChecks: List["StatusCheckConfigurationInput"]
    strictRequiredStatusChecksPolicy: bool


class RerequestCheckSuiteInput(BaseModel):
    checkSuiteId: str
    clientMutationId: Optional[str] = None
    repositoryId: str


class ResolveReviewThreadInput(BaseModel):
    clientMutationId: Optional[str] = None
    threadId: str


class RetireSponsorsTierInput(BaseModel):
    clientMutationId: Optional[str] = None
    tierId: str


class RevertPullRequestInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    draft: Optional[bool] = False
    pullRequestId: str
    title: Optional[str] = None


class RevokeEnterpriseOrganizationsMigratorRoleInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    login: str


class RevokeMigratorRoleInput(BaseModel):
    actor: str
    actorType: ActorType
    clientMutationId: Optional[str] = None
    organizationId: str


class RuleParametersInput(BaseModel):
    branchNamePattern: Optional["BranchNamePatternParametersInput"] = None
    codeScanning: Optional["CodeScanningParametersInput"] = None
    commitAuthorEmailPattern: Optional["CommitAuthorEmailPatternParametersInput"] = None
    commitMessagePattern: Optional["CommitMessagePatternParametersInput"] = None
    committerEmailPattern: Optional["CommitterEmailPatternParametersInput"] = None
    fileExtensionRestriction: Optional["FileExtensionRestrictionParametersInput"] = None
    filePathRestriction: Optional["FilePathRestrictionParametersInput"] = None
    maxFilePathLength: Optional["MaxFilePathLengthParametersInput"] = None
    maxFileSize: Optional["MaxFileSizeParametersInput"] = None
    mergeQueue: Optional["MergeQueueParametersInput"] = None
    pullRequest: Optional["PullRequestParametersInput"] = None
    requiredDeployments: Optional["RequiredDeploymentsParametersInput"] = None
    requiredStatusChecks: Optional["RequiredStatusChecksParametersInput"] = None
    tagNamePattern: Optional["TagNamePatternParametersInput"] = None
    update: Optional["UpdateParametersInput"] = None
    workflows: Optional["WorkflowsParametersInput"] = None


class SavedReplyOrder(BaseModel):
    direction: OrderDirection
    field: SavedReplyOrderField


class SecurityAdvisoryIdentifierFilter(BaseModel):
    type: SecurityAdvisoryIdentifierType
    value: str


class SecurityAdvisoryOrder(BaseModel):
    direction: OrderDirection
    field: SecurityAdvisoryOrderField


class SecurityVulnerabilityOrder(BaseModel):
    direction: OrderDirection
    field: SecurityVulnerabilityOrderField


class SetEnterpriseIdentityProviderInput(BaseModel):
    clientMutationId: Optional[str] = None
    digestMethod: SamlDigestAlgorithm
    enterpriseId: str
    idpCertificate: str
    issuer: Optional[str] = None
    signatureMethod: SamlSignatureAlgorithm
    ssoUrl: Any


class SetOrganizationInteractionLimitInput(BaseModel):
    clientMutationId: Optional[str] = None
    expiry: Optional[RepositoryInteractionLimitExpiry] = None
    limit: RepositoryInteractionLimit
    organizationId: str


class SetRepositoryInteractionLimitInput(BaseModel):
    clientMutationId: Optional[str] = None
    expiry: Optional[RepositoryInteractionLimitExpiry] = None
    limit: RepositoryInteractionLimit
    repositoryId: str


class SetUserInteractionLimitInput(BaseModel):
    clientMutationId: Optional[str] = None
    expiry: Optional[RepositoryInteractionLimitExpiry] = None
    limit: RepositoryInteractionLimit
    userId: str


class SponsorAndLifetimeValueOrder(BaseModel):
    direction: OrderDirection
    field: SponsorAndLifetimeValueOrderField


class SponsorOrder(BaseModel):
    direction: OrderDirection
    field: SponsorOrderField


class SponsorableOrder(BaseModel):
    direction: OrderDirection
    field: SponsorableOrderField


class SponsorsActivityOrder(BaseModel):
    direction: OrderDirection
    field: SponsorsActivityOrderField


class SponsorsTierOrder(BaseModel):
    direction: OrderDirection
    field: SponsorsTierOrderField


class SponsorshipNewsletterOrder(BaseModel):
    direction: OrderDirection
    field: SponsorshipNewsletterOrderField


class SponsorshipOrder(BaseModel):
    direction: OrderDirection
    field: SponsorshipOrderField


class StarOrder(BaseModel):
    direction: OrderDirection
    field: StarOrderField


class StartOrganizationMigrationInput(BaseModel):
    clientMutationId: Optional[str] = None
    sourceAccessToken: str
    sourceOrgUrl: Any
    targetEnterpriseId: str
    targetOrgName: str


class StartRepositoryMigrationInput(BaseModel):
    accessToken: Optional[str] = None
    clientMutationId: Optional[str] = None
    continueOnError: Optional[bool] = None
    gitArchiveUrl: Optional[str] = None
    githubPat: Optional[str] = None
    lockSource: Optional[bool] = None
    metadataArchiveUrl: Optional[str] = None
    ownerId: str
    repositoryName: str
    skipReleases: Optional[bool] = None
    sourceId: str
    sourceRepositoryUrl: Any
    targetRepoVisibility: Optional[str] = None


class StatusCheckConfigurationInput(BaseModel):
    context: str
    integrationId: Optional[int] = None


class SubmitPullRequestReviewInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    event: PullRequestReviewEvent
    pullRequestId: Optional[str] = None
    pullRequestReviewId: Optional[str] = None


class TagNamePatternParametersInput(BaseModel):
    name: Optional[str] = None
    negate: Optional[bool] = None
    operator: str
    pattern: str


class TeamDiscussionCommentOrder(BaseModel):
    direction: OrderDirection
    field: TeamDiscussionCommentOrderField


class TeamDiscussionOrder(BaseModel):
    direction: OrderDirection
    field: TeamDiscussionOrderField


class TeamMemberOrder(BaseModel):
    direction: OrderDirection
    field: TeamMemberOrderField


class TeamOrder(BaseModel):
    direction: OrderDirection
    field: TeamOrderField


class TeamRepositoryOrder(BaseModel):
    direction: OrderDirection
    field: TeamRepositoryOrderField


class TransferEnterpriseOrganizationInput(BaseModel):
    clientMutationId: Optional[str] = None
    destinationEnterpriseId: str
    organizationId: str


class TransferIssueInput(BaseModel):
    clientMutationId: Optional[str] = None
    createLabelsIfMissing: Optional[bool] = False
    issueId: str
    repositoryId: str


class UnarchiveProjectV2ItemInput(BaseModel):
    clientMutationId: Optional[str] = None
    itemId: str
    projectId: str


class UnarchiveRepositoryInput(BaseModel):
    clientMutationId: Optional[str] = None
    repositoryId: str


class UnfollowOrganizationInput(BaseModel):
    clientMutationId: Optional[str] = None
    organizationId: str


class UnfollowUserInput(BaseModel):
    clientMutationId: Optional[str] = None
    userId: str


class UnlinkProjectV2FromRepositoryInput(BaseModel):
    clientMutationId: Optional[str] = None
    projectId: str
    repositoryId: str


class UnlinkProjectV2FromTeamInput(BaseModel):
    clientMutationId: Optional[str] = None
    projectId: str
    teamId: str


class UnlinkRepositoryFromProjectInput(BaseModel):
    clientMutationId: Optional[str] = None
    projectId: str
    repositoryId: str


class UnlockLockableInput(BaseModel):
    clientMutationId: Optional[str] = None
    lockableId: str


class UnmarkDiscussionCommentAsAnswerInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class UnmarkFileAsViewedInput(BaseModel):
    clientMutationId: Optional[str] = None
    path: str
    pullRequestId: str


class UnmarkIssueAsDuplicateInput(BaseModel):
    canonicalId: str
    clientMutationId: Optional[str] = None
    duplicateId: str


class UnmarkProjectV2AsTemplateInput(BaseModel):
    clientMutationId: Optional[str] = None
    projectId: str


class UnminimizeCommentInput(BaseModel):
    clientMutationId: Optional[str] = None
    subjectId: str


class UnpinIssueInput(BaseModel):
    clientMutationId: Optional[str] = None
    issueId: str


class UnresolveReviewThreadInput(BaseModel):
    clientMutationId: Optional[str] = None
    threadId: str


class UpdateBranchProtectionRuleInput(BaseModel):
    allowsDeletions: Optional[bool] = None
    allowsForcePushes: Optional[bool] = None
    blocksCreations: Optional[bool] = None
    branchProtectionRuleId: str
    bypassForcePushActorIds: Optional[List[str]] = None
    bypassPullRequestActorIds: Optional[List[str]] = None
    clientMutationId: Optional[str] = None
    dismissesStaleReviews: Optional[bool] = None
    isAdminEnforced: Optional[bool] = None
    lockAllowsFetchAndMerge: Optional[bool] = None
    lockBranch: Optional[bool] = None
    pattern: Optional[str] = None
    pushActorIds: Optional[List[str]] = None
    requireLastPushApproval: Optional[bool] = None
    requiredApprovingReviewCount: Optional[int] = None
    requiredDeploymentEnvironments: Optional[List[str]] = None
    requiredStatusCheckContexts: Optional[List[str]] = None
    requiredStatusChecks: Optional[List["RequiredStatusCheckInput"]] = None
    requiresApprovingReviews: Optional[bool] = None
    requiresCodeOwnerReviews: Optional[bool] = None
    requiresCommitSignatures: Optional[bool] = None
    requiresConversationResolution: Optional[bool] = None
    requiresDeployments: Optional[bool] = None
    requiresLinearHistory: Optional[bool] = None
    requiresStatusChecks: Optional[bool] = None
    requiresStrictStatusChecks: Optional[bool] = None
    restrictsPushes: Optional[bool] = None
    restrictsReviewDismissals: Optional[bool] = None
    reviewDismissalActorIds: Optional[List[str]] = None


class UpdateCheckRunInput(BaseModel):
    actions: Optional[List["CheckRunAction"]] = None
    checkRunId: str
    clientMutationId: Optional[str] = None
    completedAt: Optional[Any] = None
    conclusion: Optional[CheckConclusionState] = None
    detailsUrl: Optional[Any] = None
    externalId: Optional[str] = None
    name: Optional[str] = None
    output: Optional["CheckRunOutput"] = None
    repositoryId: str
    startedAt: Optional[Any] = None
    status: Optional[RequestableCheckStatusState] = None


class UpdateCheckSuitePreferencesInput(BaseModel):
    autoTriggerPreferences: List["CheckSuiteAutoTriggerPreference"]
    clientMutationId: Optional[str] = None
    repositoryId: str


class UpdateDiscussionCommentInput(BaseModel):
    body: str
    clientMutationId: Optional[str] = None
    commentId: str


class UpdateDiscussionInput(BaseModel):
    body: Optional[str] = None
    categoryId: Optional[str] = None
    clientMutationId: Optional[str] = None
    discussionId: str
    title: Optional[str] = None


class UpdateEnterpriseAdministratorRoleInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    login: str
    role: EnterpriseAdministratorRole


class UpdateEnterpriseAllowPrivateRepositoryForkingSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    policyValue: Optional[EnterpriseAllowPrivateRepositoryForkingPolicyValue] = None
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseDefaultRepositoryPermissionSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseDefaultRepositoryPermissionSettingValue


class UpdateEnterpriseDeployKeySettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseMembersCanChangeRepositoryVisibilitySettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseMembersCanCreateRepositoriesSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    membersCanCreateInternalRepositories: Optional[bool] = None
    membersCanCreatePrivateRepositories: Optional[bool] = None
    membersCanCreatePublicRepositories: Optional[bool] = None
    membersCanCreateRepositoriesPolicyEnabled: Optional[bool] = None
    settingValue: Optional[EnterpriseMembersCanCreateRepositoriesSettingValue] = None


class UpdateEnterpriseMembersCanDeleteIssuesSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseMembersCanDeleteRepositoriesSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseMembersCanInviteCollaboratorsSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseMembersCanMakePurchasesSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseMembersCanMakePurchasesSettingValue


class UpdateEnterpriseMembersCanUpdateProtectedBranchesSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseMembersCanViewDependencyInsightsSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseOrganizationProjectsSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseOwnerOrganizationRoleInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    organizationId: str
    organizationRole: RoleInOrganization


class UpdateEnterpriseProfileInput(BaseModel):
    clientMutationId: Optional[str] = None
    description: Optional[str] = None
    enterpriseId: str
    location: Optional[str] = None
    name: Optional[str] = None
    websiteUrl: Optional[str] = None


class UpdateEnterpriseRepositoryProjectsSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseTeamDiscussionsSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledDisabledSettingValue


class UpdateEnterpriseTwoFactorAuthenticationDisallowedMethodsSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseDisallowedMethodsSettingValue


class UpdateEnterpriseTwoFactorAuthenticationRequiredSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    enterpriseId: str
    settingValue: EnterpriseEnabledSettingValue


class UpdateEnvironmentInput(BaseModel):
    clientMutationId: Optional[str] = None
    environmentId: str
    preventSelfReview: Optional[bool] = None
    reviewers: Optional[List[str]] = None
    waitTimer: Optional[int] = None


class UpdateIpAllowListEnabledSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    ownerId: str
    settingValue: IpAllowListEnabledSettingValue


class UpdateIpAllowListEntryInput(BaseModel):
    allowListValue: str
    clientMutationId: Optional[str] = None
    ipAllowListEntryId: str
    isActive: bool
    name: Optional[str] = None


class UpdateIpAllowListForInstalledAppsEnabledSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    ownerId: str
    settingValue: IpAllowListForInstalledAppsEnabledSettingValue


class UpdateIssueCommentInput(BaseModel):
    body: str
    clientMutationId: Optional[str] = None
    id: str


class UpdateIssueInput(BaseModel):
    assigneeIds: Optional[List[str]] = None
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    id: str
    issueTypeId: Optional[str] = None
    labelIds: Optional[List[str]] = None
    milestoneId: Optional[str] = None
    projectIds: Optional[List[str]] = None
    state: Optional[IssueState] = None
    title: Optional[str] = None


class UpdateIssueIssueTypeInput(BaseModel):
    clientMutationId: Optional[str] = None
    issueId: str
    issueTypeId: Optional[str] = None


class UpdateIssueTypeInput(BaseModel):
    clientMutationId: Optional[str] = None
    color: Optional[IssueTypeColor] = None
    description: Optional[str] = None
    isEnabled: Optional[bool] = None
    issueTypeId: str
    name: Optional[str] = None


class UpdateLabelInput(BaseModel):
    clientMutationId: Optional[str] = None
    color: Optional[str] = None
    description: Optional[str] = None
    id: str
    name: Optional[str] = None


class UpdateNotificationRestrictionSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    ownerId: str
    settingValue: NotificationRestrictionSettingValue


class UpdateOrganizationAllowPrivateRepositoryForkingSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    forkingEnabled: bool
    organizationId: str


class UpdateOrganizationWebCommitSignoffSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    organizationId: str
    webCommitSignoffRequired: bool


class UpdateParametersInput(BaseModel):
    updateAllowsFetchAndMerge: bool


class UpdatePatreonSponsorabilityInput(BaseModel):
    clientMutationId: Optional[str] = None
    enablePatreonSponsorships: bool
    sponsorableLogin: Optional[str] = None


class UpdateProjectCardInput(BaseModel):
    clientMutationId: Optional[str] = None
    isArchived: Optional[bool] = None
    note: Optional[str] = None
    projectCardId: str


class UpdateProjectColumnInput(BaseModel):
    clientMutationId: Optional[str] = None
    name: str
    projectColumnId: str


class UpdateProjectInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    name: Optional[str] = None
    projectId: str
    public: Optional[bool] = None
    state: Optional[ProjectState] = None


class UpdateProjectV2CollaboratorsInput(BaseModel):
    clientMutationId: Optional[str] = None
    collaborators: List["ProjectV2Collaborator"]
    projectId: str


class UpdateProjectV2DraftIssueInput(BaseModel):
    assigneeIds: Optional[List[str]] = None
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    draftIssueId: str
    title: Optional[str] = None


class UpdateProjectV2FieldInput(BaseModel):
    clientMutationId: Optional[str] = None
    fieldId: str
    iterationConfiguration: Optional["ProjectV2IterationFieldConfigurationInput"] = None
    name: Optional[str] = None
    singleSelectOptions: Optional[List["ProjectV2SingleSelectFieldOptionInput"]] = None


class UpdateProjectV2Input(BaseModel):
    clientMutationId: Optional[str] = None
    closed: Optional[bool] = None
    projectId: str
    public: Optional[bool] = None
    readme: Optional[str] = None
    shortDescription: Optional[str] = None
    title: Optional[str] = None


class UpdateProjectV2ItemFieldValueInput(BaseModel):
    clientMutationId: Optional[str] = None
    fieldId: str
    itemId: str
    projectId: str
    value: "ProjectV2FieldValue"


class UpdateProjectV2ItemPositionInput(BaseModel):
    afterId: Optional[str] = None
    clientMutationId: Optional[str] = None
    itemId: str
    projectId: str


class UpdateProjectV2StatusUpdateInput(BaseModel):
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    startDate: Optional[Any] = None
    status: Optional[ProjectV2StatusUpdateStatus] = None
    statusUpdateId: str
    targetDate: Optional[Any] = None


class UpdatePullRequestBranchInput(BaseModel):
    clientMutationId: Optional[str] = None
    expectedHeadOid: Optional[Any] = None
    pullRequestId: str
    updateMethod: Optional[PullRequestBranchUpdateMethod] = None


class UpdatePullRequestInput(BaseModel):
    assigneeIds: Optional[List[str]] = None
    baseRefName: Optional[str] = None
    body: Optional[str] = None
    clientMutationId: Optional[str] = None
    labelIds: Optional[List[str]] = None
    maintainerCanModify: Optional[bool] = None
    milestoneId: Optional[str] = None
    projectIds: Optional[List[str]] = None
    pullRequestId: str
    state: Optional[PullRequestUpdateState] = None
    title: Optional[str] = None


class UpdatePullRequestReviewCommentInput(BaseModel):
    body: str
    clientMutationId: Optional[str] = None
    pullRequestReviewCommentId: str


class UpdatePullRequestReviewInput(BaseModel):
    body: str
    clientMutationId: Optional[str] = None
    pullRequestReviewId: str


class UpdateRefInput(BaseModel):
    clientMutationId: Optional[str] = None
    force: Optional[bool] = False
    oid: Any
    refId: str


class UpdateRefsInput(BaseModel):
    clientMutationId: Optional[str] = None
    refUpdates: List["RefUpdate"]
    repositoryId: str


class UpdateRepositoryInput(BaseModel):
    clientMutationId: Optional[str] = None
    description: Optional[str] = None
    hasDiscussionsEnabled: Optional[bool] = None
    hasIssuesEnabled: Optional[bool] = None
    hasProjectsEnabled: Optional[bool] = None
    hasSponsorshipsEnabled: Optional[bool] = None
    hasWikiEnabled: Optional[bool] = None
    homepageUrl: Optional[Any] = None
    name: Optional[str] = None
    repositoryId: str
    template: Optional[bool] = None


class UpdateRepositoryRulesetInput(BaseModel):
    bypassActors: Optional[List["RepositoryRulesetBypassActorInput"]] = None
    clientMutationId: Optional[str] = None
    conditions: Optional["RepositoryRuleConditionsInput"] = None
    enforcement: Optional[RuleEnforcement] = None
    name: Optional[str] = None
    repositoryRulesetId: str
    rules: Optional[List["RepositoryRuleInput"]] = None
    target: Optional[RepositoryRulesetTarget] = None


class UpdateRepositoryWebCommitSignoffSettingInput(BaseModel):
    clientMutationId: Optional[str] = None
    repositoryId: str
    webCommitSignoffRequired: bool


class UpdateSponsorshipPreferencesInput(BaseModel):
    clientMutationId: Optional[str] = None
    privacyLevel: Optional[SponsorshipPrivacy] = SponsorshipPrivacy.PUBLIC
    receiveEmails: Optional[bool] = True
    sponsorId: Optional[str] = None
    sponsorLogin: Optional[str] = None
    sponsorableId: Optional[str] = None
    sponsorableLogin: Optional[str] = None


class UpdateSubscriptionInput(BaseModel):
    clientMutationId: Optional[str] = None
    state: SubscriptionState
    subscribableId: str


class UpdateTeamDiscussionCommentInput(BaseModel):
    body: str
    bodyVersion: Optional[str] = None
    clientMutationId: Optional[str] = None
    id: str


class UpdateTeamDiscussionInput(BaseModel):
    body: Optional[str] = None
    bodyVersion: Optional[str] = None
    clientMutationId: Optional[str] = None
    id: str
    pinned: Optional[bool] = None
    title: Optional[str] = None


class UpdateTeamReviewAssignmentInput(BaseModel):
    algorithm: Optional[TeamReviewAssignmentAlgorithm] = (
        TeamReviewAssignmentAlgorithm.ROUND_ROBIN
    )
    clientMutationId: Optional[str] = None
    countMembersAlreadyRequested: Optional[bool] = True
    enabled: bool
    excludedTeamMemberIds: Optional[List[str]] = None
    id: str
    includeChildTeamMembers: Optional[bool] = True
    notifyTeam: Optional[bool] = True
    removeTeamRequest: Optional[bool] = True
    teamMemberCount: Optional[int] = 1


class UpdateTeamsRepositoryInput(BaseModel):
    clientMutationId: Optional[str] = None
    permission: RepositoryPermission
    repositoryId: str
    teamIds: List[str]


class UpdateTopicsInput(BaseModel):
    clientMutationId: Optional[str] = None
    repositoryId: str
    topicNames: List[str]


class UpdateUserListInput(BaseModel):
    clientMutationId: Optional[str] = None
    description: Optional[str] = None
    isPrivate: Optional[bool] = None
    listId: str
    name: Optional[str] = None


class UpdateUserListsForItemInput(BaseModel):
    clientMutationId: Optional[str] = None
    itemId: str
    listIds: List[str]
    suggestedListIds: Optional[List[str]] = None


class UserStatusOrder(BaseModel):
    direction: OrderDirection
    field: UserStatusOrderField


class VerifiableDomainOrder(BaseModel):
    direction: OrderDirection
    field: VerifiableDomainOrderField


class VerifyVerifiableDomainInput(BaseModel):
    clientMutationId: Optional[str] = None
    id: str


class WorkflowFileReferenceInput(BaseModel):
    path: str
    ref: Optional[str] = None
    repositoryId: int
    sha: Optional[str] = None


class WorkflowRunOrder(BaseModel):
    direction: OrderDirection
    field: WorkflowRunOrderField


class WorkflowsParametersInput(BaseModel):
    doNotEnforceOnCreate: Optional[bool] = None
    workflows: List["WorkflowFileReferenceInput"]


AddPullRequestReviewInput.model_rebuild()
CheckAnnotationData.model_rebuild()
CheckRunOutput.model_rebuild()
CodeScanningParametersInput.model_rebuild()
CreateBranchProtectionRuleInput.model_rebuild()
CreateCheckRunInput.model_rebuild()
CreateCommitOnBranchInput.model_rebuild()
CreateProjectV2FieldInput.model_rebuild()
CreateRepositoryRulesetInput.model_rebuild()
CreateSponsorshipsInput.model_rebuild()
FileChanges.model_rebuild()
ImportProjectInput.model_rebuild()
ProjectColumnImport.model_rebuild()
ProjectV2IterationFieldConfigurationInput.model_rebuild()
RepositoryPropertyConditionTargetInput.model_rebuild()
RepositoryRuleConditionsInput.model_rebuild()
RepositoryRuleInput.model_rebuild()
RequiredStatusChecksParametersInput.model_rebuild()
RuleParametersInput.model_rebuild()
UpdateBranchProtectionRuleInput.model_rebuild()
UpdateCheckRunInput.model_rebuild()
UpdateCheckSuitePreferencesInput.model_rebuild()
UpdateProjectV2CollaboratorsInput.model_rebuild()
UpdateProjectV2FieldInput.model_rebuild()
UpdateProjectV2ItemFieldValueInput.model_rebuild()
UpdateRefsInput.model_rebuild()
UpdateRepositoryRulesetInput.model_rebuild()
WorkflowsParametersInput.model_rebuild()
