name: Generate Python GraphQL Client
on: [workflow_dispatch]
jobs:
  generate_graphql_client:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ariadne-codegen

      - name: Generate GraphQL client
        run: |
          GITHUB_GRAPHQL_CLIENT=/tmp/github_graphql_client
          GITHUB_GRAPHQL_GENERATOR_CONFIG="$GITHUB_WORKSPACE/.github/workflows/generate_graphql_client_config.toml"

          mkdir "$GITHUB_GRAPHQL_CLIENT"
          cp "$GITHUB_GRAPHQL_GENERATOR_CONFIG" "$GITHUB_GRAPHQL_CLIENT/pyproject.toml"
          curl "https://docs.github.com/public/fpt/schema.docs.graphql" -o "$GITHUB_GRAPHQL_CLIENT/schema.graphql"

          (cd "$GITHUB_GRAPHQL_CLIENT" && ariadne-codegen client)

          cp -r "$GITHUB_GRAPHQL_CLIENT/graphql_client" .

      - name: Patch generated GraphQL client
        run: |
          for file in .github/workflows/graphql_client_patches/*.patch; do
            git apply "$file"
          done

      - name: Push generated GraphQL client to repository
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: "Naucto GraphQL Client Generator"
          message: "[CLIENT] [UPDATE] Update auto-generated GraphQL client"
